# https://gist.github.com/containeroo-gists/0e79fb145252611ee1bb0da2c31f243d
# https://gist.github.com/containeroo-gists/27666fe7d32199f40c01b20f49cc0454
global:
  checkNewVersion: false
  sendAnonymousUsage: false

#entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf

# API and dashboard configuration
#api:
#  dashboard: false

log:
  level: INFO

accessLog:
  filters:
    statusCodes:
      - "400-600"
    # default format: <remote_IP_address> - <client_user_name_if_available> [<timestamp>] "<request_method> <request_path> <request_protocol>" <origin_server_HTTP_status> <origin_server_content_size> "<request_referrer>" "<request_user_agent>" <number_of_requests_received_since_Traefik_started> "<Traefik_frontend_name>" "<Traefik_backend_URL>" <request_duration_in_ms>ms 
    retryAttempts: true
    minDuration: "200ms"

# https://community.traefik.io/t/insecureskipverify-explanation/2195
# Required for traefik --> Unifi Controller (:8443)
serversTransport:
  insecureSkipVerify: true