version: '3.5'

services:
  unifi:
    image: linuxserver/unifi-controller:latest
    container_name: unifi
    hostname: unifi
    restart: unless-stopped
#    depends_on:
#      - traefik_main
    networks:
      - traefik_traefik_proxy_unifi
    ports:
      - "3478:3478/udp"
      # Port used for device and controller communication.
      - "8080:8080"
      # - "8081:8081"
      # Port used for controller GUI/API as seen in a web browser
      #- "8443:8443"
      # Port used for HTTPS portal redirection.
      #- "8843:8843"
      # Port used for HTTP portal redirection.
      - "8880:8880"
      # Port used for device discovery
      - "10001:10001/udp"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - "./docker/unifi:/config"
      - "./shared:/shared"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik_proxy_unifi"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.rule=Host(`${my_unifi_host}`)"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.tls.certresolver=leresolver"
      - "traefik.http.routers.unifi.tls.domains[0].main=${my_unifi_host}"
      - "traefik.http.routers.unifi.tls.domains[0].sans=otherfqdnalias"
      - "traefik.http.routers.unifi.service=unifi"
      - "traefik.http.routers.unifi.middlewares=unifiHeaders@file"
#      - "traefik.http.routers.unifi-ssl.middlewares=unifiHeaders@file"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
#      - "traefik.http.services.unifi.loadbalancer.server.port=8843"

      - "traefik.http.routers.unifi-guest.entrypoints=webunifiguest"
      - "traefik.http.routers.unifi-guest.rule=Host(`${my_unifi_host}`)"
      - "traefik.http.routers.unifi-guest.tls=true"
      - "traefik.http.routers.unifi-guest.tls.certresolver=leresolver"
      - "traefik.http.routers.unifi-guest.tls.domains[0].main=${my_unifi_host}"
#      - "traefik.http.routers.unifi-guest.tls.domains[0].sans=otherfqdnalias"
      - "traefik.http.routers.unifi-guest.service=unifi-guest"
#      - "traefik.http.routers.unifi-guest.middlewares=unifiHeaders@file"
#      - "traefik.http.routers.unifi-ssl.middlewares=unifiHeaders@file"
      - "traefik.http.services.unifi-guest.loadbalancer.server.port=8843"
      - "traefik.http.services.unifi-guest.loadbalancer.server.scheme=https"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    mem_limit: 1500M


networks:
  traefik_traefik_proxy_unifi:
    external: true

#volumes:
#  unifi_data:
